config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index' 

  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions"}

  scope "/api" do
    resources :equipments, controller: "equipment_api"
  
  end
 
 
  resources :users do
      resources :equipments
  end
  resources :equipments do
      resources :maintenances
  end
  resources :equipments do
      resources :rentals
  end

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	has_many :rentals
	
	has_many :maintenances

	belongs_to :user

	validates :name, :model, :serial, :brand, :purchased_date, :original_price, presence: true

	has_attached_file :image, styles: { thumb: "50x50" }, default_url: "/images/:style/"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
     before_action :authenticate_user!
	def index
      

		 equipments = current_user.equipment.all
        if equipments.length < 1
            @vartime_now = time_now
            render "no_eqipments_page"
            return
        end
        @array_audio=[]
        @array_video=[]
        @array_light=[]
        @array_staging=[]
        @array_itcomputer=[]
#================================================================
#to calculate totals
        @total_investment=0
        @total_maintenances_invest=0
        @total_rentals=0

#================================================================
    
	  equipments.each do |equipment|
		if equipment.category =="AUDIO"
		              
		    @array_audio.push(equipment)           
		              
		  elsif equipment.category =="VIDEO"

		    @array_video.push(equipment)

		  elsif equipment.category =="LIGHT"   

		    @array_light.push(equipment)

		  elsif equipment.category =="STAGING" 

		    @array_staging.push(equipment)
		          
		  elsif equipment.category =="ITCOMPUTER"

            @array_itcomputer.push(equipment)
		  end

# to calculate the all investment equipment
#================================================================
      equipment.maintenances.each do |one_maintenance|
          @total_maintenances_invest=@total_maintenances_invest+one_maintenance.price
        end
       @total_investment = @total_investment +  equipment.original_price
       @total_investment = @total_investment.round(2) + @total_maintenances_invest
       @total_maintenances_invest = 0
	  
#================================================================


# to calculate the all rentals equipment
#================================================================
    equipment.rentals.each do |one_rental|
          @total_rentals=@total_rentals.round(2)+one_rental.total_price
        end    
     end
#================================================================
        @vartime_now = time_now
        render "index"
	end
	def show#current_user.
        @one_equipment = current_user.equipment.find(params[:id])

		if @one_equipment.nil?
            render "no_eqipments_page"
            return
        end

        if @one_equipment.user_id != current_user.id
            redirect_to "/"
            return
        end

        maintenances=@one_equipment.maintenances
        #"DESC"
        @maintenances=maintenances.sort {|a,b| b.date <=> a.date}


        rentals=@one_equipment.rentals
        #"DESC"
        @rentals=rentals.sort {|a,b| b.date <=> a.date}


        @totalprice_less_rentals=current_data_rentals(@one_equipment,@rentals)
        @totalprice_plus_maintenances=current_data_maintenances(@one_equipment,@maintenances, @rentals)
        @profit= profit_calculation(@one_equipment, @totalprice_plus_maintenances)


        @running_time_from_days = running_time(@one_equipment)
                                
          
          # puts ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
          @running_time_from = (@running_time_from_days/ 365)
          auxtimefloat=(@running_time_from_days.to_f / 365)
      
          auxtimefloat = auxtimefloat.modulo(1)
          # puts ("antes")
          # puts (@running_time_from_days)
          # puts (auxtimefloat)
          @running_time_from_days = auxtimefloat * 365
          @running_time_from_days = @running_time_from_days.round
          # puts ("despues")
          # puts (@running_time_from_days)
          # puts (@running_time_from)
          # puts (auxtimefloat)
          # puts ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
     
       @depretation = straight_linedepreciation(@one_equipment, @running_time_from)


        @vartime_now = time_now
		render "show"
	end


    def update
        @one_equipment = current_user.equipment.find(params[:id])
        if @one_equipment.nil?
            render "no_eqipments_page"
            return
        end
       if params[:equipment] != nil
            if params[:equipment][:image] != nil
                if @one_equipment.update(:image => params[:equipment][:image])
                    redirect_to "/equipments/"+params[:id]
                else 
                    redirect_to "/users/sign_up"
                end 
            end 
        else 
            redirect_to "/equipments/"+params[:id]
        end
    end



    private
	def current_data_maintenances(one_equipment,maintenances, rentals)
       
        totalprice_maintenances = current_data_rentals(one_equipment, rentals)
        maintenances.each do |one_maintenance|
        	totalprice_maintenances=totalprice_maintenances+one_maintenance.price
        end
        return totalprice_maintenances
	end
	def current_data_rentals(one_equipment,rentals)
       
        totalprice_rentals= one_equipment.original_price
        rentals.each do |one_rental|
        	totalprice_rentals=totalprice_rentals-one_rental.total_price
        end
        return totalprice_rentals
	end
	def profit_calculation(one_equipment, totalprice_plus_maintenances)
        profitvar = 0
		if totalprice_plus_maintenances >= 0
           profitvar = 0
		elsif totalprice_plus_maintenances < 0
           profitvar=totalprice_plus_maintenances.abs
        end

      return profitvar
	end
	def running_time(one_equipment)

         #puts ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
         #puts (one_equipment.purchased_date)
         #puts (one_equipment.purchased_date)
         #puts ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        running_time_from = (Date.today.mjd - one_equipment.purchased_date.mjd)#.to_f

        return running_time_from
	end
	def time_now
		vartime_now=Date.today
		return vartime_now
	end
  def straight_linedepreciation (one_equipment, running_time)
    salvage = one_equipment.original_price * 0.012
    if one_equipment.category =="AUDIO"
        lifetime = 12;
        if running_time >= lifetime
          depretation = salvage
        else
          depretation = (one_equipment.original_price -  salvage) / lifetime
          depretation = running_time * depretation
          depretation = one_equipment.original_price - depretation
        end
                  
     elsif one_equipment.category =="VIDEO"
       lifetime = 9;
        if running_time >= lifetime
          depretation = salvage
        else
          depretation = (one_equipment.original_price -  salvage) / lifetime
          depretation = running_time * depretation
          depretation = one_equipment.original_price - depretation
        end
     elsif one_equipment.category =="LIGHT"   
        lifetime = 10;
        if running_time >= lifetime
          depretation = salvage
        else
          depretation = (one_equipment.original_price -  salvage) / lifetime
          depretation = running_time * depretation
          depretation = one_equipment.original_price - depretation
        end
     elsif one_equipment.category =="STAGING" 
        lifetime = 12;
        if running_time >= lifetime
          depretation = salvage
        else
          depretation = (one_equipment.original_price -  salvage) / lifetime
          depretation = running_time * depretation
          depretation = one_equipment.original_price - depretation
        end
                             
    elsif one_equipment.category =="ITCOMPUTER"
          lifetime = 4;
        if running_time >= lifetime
          depretation = salvage
        else
          depretation = (one_equipment.original_price -  salvage) / lifetime
          depretation = running_time * depretation
          depretation = one_equipment.original_price - depretation
        end
    end   
       return depretation.round(2)
  end
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/views/equipments/index.html.erb
<div class="container-fluid">
   <div class="row">
      <%=image_tag("logotop", class: "imgtop")%>
   </div> <!--close div cintillo-->

   
   <div class="row">
       
          <a class="cornerleft1" href="/">home</a>
      
          <%if user_signed_in?%>       
             <t class="cornerrigth3"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %><t/>
             <t class="corneruserimg">&nbsp<%= image_tag current_user.image.url(:thumb)%></t><br>
             <t class="cornerrigth"><strong><a href="/users/edit">User: </a></strong> <%=current_user.name%>&nbsp</t>

          <%else%>
             <a class="logout" href="/users/sign_in">Login |</a>
             <a class="logout" href="/users/sign_up">Sign up</a>
          <%end%>  

   </div><!-- first row close-->




   <div class="row addequip">
         <button class="btn btn-primary js-new_equip">add equipment</button>
         <strong class="letterlistequipment1 js-timenow" data-timedatenow="<%= @vartime_now %>"></strong>
         <br>
         <br>
 <!--totals invest in equipment*********************************-->         
         <div class="investmentcol">
               <t class="letterlistequipment1especial1">Total Business Investment : </t><strong><%=@total_investment%></strong>
               <br>
             
               <t class="letterlistequipment1especial1 dollars">Total Rentals: </t><strong><%=@total_rentals%></strong>
               <br>
               <t class="letterlistequipment1especial1">Total PROFIT : </t><strong><%= @total_rentals-@total_investment%></strong>
         </div>
  <!--**********************************************************-->
   </div><!-- 2da row close-->

  
   <div class="row">

              

              <div class="col-sm-2 audiocol">
                 <strong>Audio</strong><p>
                 <br>
                <ul>
                  <%if @array_audio.length > 0%>
                    <% @array_audio.each do |one_audio|%>
                       <a href="/equipments/<%=one_audio.id%>">
                       <li class="letterlistequipment">
                         <strong> Name: </strong> <%=one_audio.name%><br>
                         <strong> Serial: </strong> <%=one_audio.serial%>
                       </li>
                       </a><br>
                    <%end%>
                  <%end%>
                </ul>
             </div><!-- 1er column--> 

             

             <div class="col-sm-2 videocol">
                    <strong>Video</strong><p>
              <br>
                <ul>
                <%if @array_video.length > 0%>
                   <% @array_video.each do |one_video|%>
                       <a href="/equipments/<%=one_video.id%>">
                       <li class="letterlistequipment">
                         <strong> Name: </strong> <%=one_video.name%><br>
                         <strong> Serial: </strong> <%=one_video.serial%>
                       </li>
                       </a><br>
                    <%end%>
                <%end%>
                </ul>
             </div><!-- 2da column-->

            

             <div class="col-sm-2 lightcol">
              <strong>Light</strong><p>
              <br>
                  <ul>
                  <%if @array_light.length > 0%>
                    <% @array_light.each do |one_light|%>
                       <a href="/equipments/<%=one_light.id%>">
                       <li class="letterlistequipment">
                         <strong> Name: </strong><%=one_light.name%><br>
                         <strong> Serial: </strong> <%=one_light.serial%>
                       </li>
                       </a><br>
                    <%end%>
                  <%end%>
                  </ul>
             </div><!-- 3er column-->

            

             <div class="col-sm-2 stagingcol">
              <strong>Staging</strong><p>
              <br>
              <ul>
                <%if @array_staging.length > 0%>
                 <% @array_staging.each do |one_staging|%>
                       <a href="/equipments/<%=one_staging.id%>">
                       <li class="letterlistequipment">
                         <strong> Name: </strong><%=one_staging.name%><br>
                         <strong> Serial: </strong> <%=one_staging.serial%>
                       </li>
                       </a><br>
                    <%end%>
                <%end%>
              </ul>
             </div><!-- 4da column--> 
          
            

             <div class="col-sm-2 itcomputercol">
                <strong>IT/Computer</strong><p>
                <br>
                <ul>
                  <%if @array_itcomputer.length > 0%>
                   <% @array_itcomputer.each do |one_itcomputer|%>
                       <a href="/equipments/<%=one_itcomputer.id%>">
                       <li class="letterlistequipment">
                        <strong> Name: </strong> <%=one_itcomputer.name%><br>
                        <strong>Serial: </strong><%=one_itcomputer.serial%>
                       </li>
                       </a><br>
                    <%end%>
                  <%end%>
                </ul>
             </div><!-- 5ta column--> 

   

  <!-- agregue el modal que va a destruir mi codigo-->

      <div class="modal fade js-modal">
        <div class="modal-dialog">
          <div class="modal-content">

            <div class="modal-header">
              <!-- Close button -->
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span>&times;</span>
              </button>

              <h2 class="modal_title"></h2>
            </div>

            <div class="modal-body">
              <p>This is the modal's body.</p>
            </div>

          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

<!-- final del modal que va a destruir mi codigo-->

    </div><!-- 4ta row close-->
       <div class="row">
     
       <br></br>
    </div>
  <footer>
    <p>
    <br>
    <div class="row">
        <%=image_tag("logofooter", class: "imgfooter")%>
    </div><!--Close footer-->
  </footer>
</div><!-- container -->

app/views/equipments/no_eqipments_page.html.erb
<div class="container-fluid">

	<div class="row">
      <%=image_tag("logotop", class: "imgtop")%>
   </div> <!--close div cintillo-->
  
    <div class="row">
        <h1>You have no equipments<h1>
        <a class="cornerleft1" href="/">home</a>
        <strong class="letterlistequipment1 js-timenow" data-timedatenow="<%= @vartime_now %>"></strong>
        <%if user_signed_in?%>       
           <t class="cornerrigth3"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %><t/>
           <t class="corneruserimg">&nbsp<%= image_tag current_user.image.url(:thumb)%></t><br>
           <t class="cornerrigth"><strong><a href="/users/edit">User: </a></strong> <%=current_user.name%>&nbsp</t>

        <%else%>
           <a class="logout" href="/users/sign_in">Login |</a>
           <a class="logout" href="/users/sign_up">Sign up</a>
        <%end%>  

    </div>
    <div class="row addequip">
         <button class="btn btn-primary js-new_equip">add equipment</button>
       </div><!-- 3ra row close-->
    <div class="row">
    	 <%=image_tag("fuel", class: "logocenterfuel")%>
    </div>


 <!-- agregue el modal que va a destruir mi codigo-->

      <div class="modal fade js-modal">
        <div class="modal-dialog">
          <div class="modal-content">

            <div class="modal-header">
              <!-- Close button -->
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span>&times;</span>
              </button>

              <h2 class="modal_title"></h2>
            </div>

            <div class="modal-body">
              <p>This is the modal's body.</p>
            </div>

          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

<!-- final del modal que va a destruir mi codigo-->






<footer>
    <div class="row">
        <%=image_tag("logofooter", class: "imgfooter")%>
    </div><!--Close footer-->
</footer>

</div> <!--Close container-->

app/views/equipments/show.html.erb
<div class="container-fluid">
   <div class="row">
      <%=image_tag("logotop", class: "imgtop")%>
   </div> <!--close div cintillo-->

   <div class="row">
       
          <a class="cornerleft1" href="/">home | </a>
          <a class="cornerleft1especial" href="/equipments">List Equipment</a> 
          <%if user_signed_in?%>       
             <t class="cornerrigth3"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %><t/>
             <t class="corneruserimg">&nbsp<%= image_tag current_user.image.url(:thumb)%></t><br>
             <t class="cornerrigth"><strong><a href="/users/edit">User: </a></strong> <%=current_user.name%>&nbsp</t>

          <%else%>
             <a class="logout" href="/users/sign_in">Login |</a>
             <a class="logout" href="/users/sign_up">Sign up</a>
          <%end%>  
     <br>
     <br>
     <br>
   </div><!-- first row close-->

   <div class="row">
      <div class="col-sm-3 equipmentcol">
          <strong>Equipment</strong><p>



             <button class="btn btn-primary updateequi js-updateequi" data-equip="<%= @one_equipment.id %>">update</button>
             <button class="btn btn-danger deleteequi js-deleteequi" data-equip="<%= @one_equipment.id %>">delete</button><p>
          <br>
          <ul>
           
            <%=image_tag(@one_equipment.image, class: "equipplaceholder")%>
            <li class="letterlistequipment"><strong>NAME: </strong><%=@one_equipment.name%></li>
            <li class="letterlistequipment"><strong>MODEL: </strong><%=@one_equipment.model%></li>
            <li class="letterlistequipment"><strong>SERIAL: </strong><%=@one_equipment.serial%></li>
            <li class="letterlistequipment"><strong>BRAND: </strong><%=@one_equipment.brand%></li>

            <li class="letterlistequipment"><strong class="datepurcharsed_valid"data-datepur="<%= @one_equipment.purchased_date%>">PURCHASED DATE: </strong><%=@one_equipment.purchased_date%></li>

            <li class="letterlistequipment"><strong>ORIGINAL PRICE: </strong><%=@one_equipment.original_price%></li>
          </ul>


<!--+++++++++++++++++++++++++++++++++tratando de hacer la foto 12-05-2016++++++++++++++++++++-->
           <div class="row img_move">
                <%= form_for [current_user, @one_equipment], url: user_equipment_path(current_user, @one_equipment) do | f | %>
                   <%= f.file_field :image, autocomplete: "off", :class => "letter"%><br>
                   <%= f.button "save photo", :class => 'btn btn-primary letter'%>
                <% end %>
              </div>
<!--+++++++++++++++++++++++++++++++++tratando de hacer la foto 12-05-2016++++++++++++++++++++-->             
          <div class="row updatedeleteequip">
            
          </div><!--Close row button-->

           
      </div><!-- 1er column--> 
 
      <div class="col-sm-2 maintecol">

          <!-- <div class="row"> -->
                      
               <!--<br>-->

          <!--</div>--><!--Close row button-->

         <strong>MINUS: Accessories</strong><p>
         <strong>and Maintenances</strong><br>
         <button class="btn btn-primary addmainte js-addmainte">add new</button><p>
      
          <ul>
            <%if @maintenances.length > 0%>
               <% @maintenances.each do |one_maintenance|%>
                 <a href="#" class="js-clickmanintenances" data-mainte="<%=  one_maintenance.id%>">
                 <li class="letterlistequipment"><strong>NAME: </strong><%=one_maintenance.name%></li>
                 <li class="letterlistequipment"><strong>DESCRIPTION: </strong><%=one_maintenance.description%> </li>
                 <li class="letterlistequipment"><strong>DATE: </strong><%=one_maintenance.date%></li>
                 <li class="letterlistequipment"><strong>PRICE: </strong><%=one_maintenance.price%></li>
                 <br>
               </a>
                <%end%>
            <%end%>
          </ul>

          

       </div><!-- 2da column-->


       <div class="col-sm-2 rentalcol">
           <strong>Rentals</strong><p><br>
             <button class="btn btn-primary addrental js-addrental">add new</button><p>
           
            <ul>
              <%if @rentals.length > 0%>
                 <% @rentals.each do |one_rental|%>
                  <a href="#" class="js-clickrentals" data-rental="<%= one_rental.id%>">
                     <li class="letterlistequipment"><strong>NAME: </strong><%=one_rental.name%></li>
                     <li class="letterlistequipment"><strong>DATE: </strong><%=one_rental.date%></li>
                     <li class="letterlistequipment"><strong>TOTAL PRICE RENTAL: </strong><%=one_rental.total_price%></li>
                     <br>
                  </a>
                 <%end%>
              <%end%>
            </ul>
            <!--<div class="row">-->
              
               <!--<br>-->
          <!--</div>--><!--Close row button-->

       </div><!-- 3er column-->


      <div class="col-sm-3 currentcol">
        <strong>Current DATA</strong><p>

          <button class="btn btn-primary sendemail js-createpdf" data-equip="<%= @one_equipment.id %>">create PDF</button><p>
      <ul>
            <li class="letterlistequipment2"><strong>Current Difference against original price: </strong></br>
                 <t class="letterlistequipment1">&nbsp $</t> 
                 <%if @totalprice_less_rentals > 0 %>
                       <strong class="letterred letterlistequipment1 js-pricelessrental"><%=@totalprice_less_rentals.round(2)%> </strong>
                    <%else%>

                       <strong class="letterlistequipment1 js-pricelessrental"><%=@totalprice_less_rentals.round(2)%></strong>
                <%end%>

            </li>
       
      

            <li class="letterlistequipment2"><strong>Current Difference against original price  plus cost of all maintenance: </strong> 
              <t class="letterlistequipment1">&nbsp $</t>
                   <%if @totalprice_plus_maintenances > 0 %>
                        <strong class="letterred letterlistequipment1 js-priceplusmainte"><%=@totalprice_plus_maintenances.round(2)%> </strong><br>
                   <%else%>
                        <strong class="letterlistequipment1 js-priceplusmainte" ><%=@totalprice_plus_maintenances.round(2)%></strong><br>         
                   <%end%>
                
            </li>
                 
                  <li class="letterlistequipment2"><strong>Price after depreciation: <a href="#"class="js-depretaicioninfo2">(info)</a></strong>
                    <t class="letterlistequipment1">&nbsp $</t>
                  <strong class="letterlistequipment1 js-depretaicioninfo"><%=@depretation.round(2)%> </strong>

                  </li> 


                     <%if @profit <= 0 %>
                        <li class="letterlistequipment2"><strong class="letterred">PROFIT: </strong>
                          <t class="letterlistequipment1">&nbsp $</t>
                          <strong class="letterred letterlistequipment1 js-profit"><%=@profit.round(2)%> </strong>

                        </li>
                     <%else%>
                          <li class="letterlistequipment2"><strong class="letterblue">PROFIT: </strong>
                          <t class="letterlistequipment1">&nbsp $</t>
                          <strong class="letterblue letterlistequipment1 js-profit"><%=@profit.round(2)%></strong> 
                         </li>
                     <%end%>



                <li class="letterlistequipment2"><strong class="letterorange">RUNNING TIME: </strong>
                   
                      
                      <t class="letterlistequipment1especial2">&nbsp days</t>
                     
                      <strong class="letterorange letterlistequipment1especial js-runningtimedays"><%=@running_time_from_days%>  </strong><br>
                      <t class="letterlistequipment1especial3">&nbsp years</t>
                      <strong class="letterorange letterlistequipment1especial4 js-runningtime"> <%=@running_time_from%></strong>
                </li>
                <li>
                  <li class="letterlistequipment2">
                    <strong>Apply Discount miscellaneous expenses:</strong>
                    <select class="form-control" id="js-discount">
                         <option value=" ">- Select one Discount option -</option>
                         <option value="0.05">- 5%</option>
                         <option value="0.10">- 10%</option>  
                         <option value="0.15">- 15%</option>
                         <option value="0.20">- 20%</option>
                         <option value="0.25">- 25%</option>
                         <option value="0.30">- 30%</option>
                         <option value="0.35">- 35%</option>
                         <option value="0.40">- 40%</option>
                         <option value="0.45">- 45%</option>    
                         <option value="0.50">- 50%</option>  
                         <option value="0.55">- 55%</option>
                         <option value="0.60">- 60%</option>
                         <option value="0.65">- 65%</option>
                         <option value="0.70">- 70%</option>
                         <option value="0.75">- 75%</option>
                         <option value="0.80">- 80%</option>   
                         <option value="0.85">- 85%</option>  
                         <option value="0.90">- 90%</option>  
                         <option value="0.95">- 95%</option>           
                    </select>
                  </li>
              
                <li class="letterlistequipment2">
                     <strong >REPORT DATE: </strong>
                 
                     <strong class="letterlistequipment1 js-timenow"><%=@vartime_now%> </strong>
                </li>
      </ul><!--Close UL Current data--> 
           <!--<div class="row">-->
                
               <!--<br>-->
           <!--</div>--><!--Close row button-->
          
      </div><!-- 4da column--> 
      

    
    </div><!-- 3era row close-->

    
    <!-- agregue el modal que va a destruir mi codigo-->

<div class="modal fade js-modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <!-- Close button -->
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span>&times;</span>
        </button>

        <h2 class="modal_title"></h2>
      </div>

      <div class="modal-body">
        <p>This is the modal's body.</p>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- final del modal que va a destruir mi codigo-->



<footer>
  <p>
    <br>
    <div class="row">
        <%=image_tag("logofooter", class: "imgfooter")%>
    </div><!--Close footer-->
</footer>
</div><!-- container -->